---
config:
  theme: default
---
sequenceDiagram
    %% Define participants with aliases for cleaner labels
    box rgb(255, 204, 204)
        participant ADP as TWIN Adaptor
    end
    participant DSC as DS Connector
    box rgb(173, 216, 230)
        participant DSApp as DS App
    end
    participant RM as Rights<br>Management
    participant DM as Document<br>Management

    autonumber

    activate ADP
    activate DSC
    ADP->>DSC: outbox(identity, <br>AS('Add', 'Document'))
    activate DSC
    DSC->>-DSC: verify
    DSC->>+RM: enforcePolicy
    RM-->>-DSC: permit
    par
        DSC-->>ADP: Accepted
        deactivate ADP
    and
        DSC->>+DSApp: handleActivity
        DSApp->>+ADP: fetchDocument
        ADP-->>DSApp: document
        deactivate ADP
        DSApp->>+DM: createDoc(fingerprint,href,target)
        DM-->>DSApp: created
        deactivate DM
        DSApp-->>DSC: activityProcessed
        deactivate DSApp
   end

deactivate DSC
