---
config:
  theme: default
---
sequenceDiagram
    %% Define participants with aliases for cleaner labels
    participant C as Client
    participant AIG as Auditable<br>Item<br>Graph
    participant DS as Datastore Connector
    participant DLT as DLT Connector
    autonumber

    activate C
    %% Step 1: Client initiates
    C->>+AIG: createVertex(annotationObject)

    activate AIG
    AIG-->>-AIG: calculate changeset
    AIG->>+DS: set(vertex)
    DS-->>-AIG: created

    par
        AIG-->>C: Response (vertexId)
        deactivate C
    and
        activate AIG
        AIG-->>-AIG: calculate<br>proof
        activate DLT
        AIG->>DLT: AuditTrail.create()
        DLT-->>-AIG: receipt(trailID)
        activate DLT
        AIG->>DLT: AuditTrail.append(trailID,proof)
        DLT-->>-AIG: receipt(recordID)
        activate AIG
        AIG->>-AIG: addResource(type=AuditTrail, id=trailID)
        AIG->>+DS: set(vertextId, vertex, auditTrailResource)
        DS-->>-AIG: updated
    end
    %% PARALLEL TASKS END HERE
    %% Manually deactivate AIG after all parallel tasks finish
    deactivate AIG
