---
config:
  theme: default
---
sequenceDiagram
    %% Define participants with aliases for cleaner labels
   box rgb(255, 204, 204)
        participant ADP as TWIN Adaptor
    end
    participant DSC as DS Connector
    box rgb(173, 216, 230)
        participant DSApp as DS App
    end
    participant RM as Rights<br>Management
    participant AIG as Auditable<br>Item<br>Graph
    

    autonumber

    activate ADP
    activate DSC
    ADP->>DSC: outbox(identity, <br>AS('Create', 'Consignment'))
    activate DSC
    DSC->>-DSC: verify
    activate RM
    DSC->>+RM: enforcePolicy
    RM->>-RM: resolve attributes  
    RM->>+RM: decide
    RM-->>-DSC: permit
    deactivate RM 
    par
        activate ADP
        DSC-->>ADP: Accepted
        deactivate ADP
    and
        DSC->>+DSApp: handleActivity
        DSApp->>+AIG: createVertex(activity.object)
        AIG-->>DSApp: created
        deactivate AIG
        DSApp-->>DSC: activityProcessed
        deactivate DSApp
   end

deactivate DSC
