---
config:
  theme: 'neutral'
---

classDiagram
    class DPI["Digital Public Infrastructure"]
     class Node {
        + owner : DID
        + endpoint 
    }
    class BackingService ["Backing Service"] {
        <<persistence>>
    }
     class Connector2["Infra Connector"] {
        + type: String
        + name: String
        + endpoint
    }
    class Component {
        + type: String
        + name: String
    }
    class ComponentManager["Component Manager"] {
        + getComponent(name: String)
    }
    class Service ["Component Service"] {
        restRoute: String
    }
    class Connector["Infra Connector"] {
        + type: String
        + name: String
        + endpoint
    }
    class Interface {
        + name: String
    }
    class Primitive {
        + signature
    }
    class VisibilityService["Visibility Service"]
    class DXService["Data Exchange Service"]
    class FedService["Federation Service"]
    class Adaptor {
        systemAdapted: String
        endpoint: String
    }
    class DSConnector["DS Connector"] {
        + registerDSApp(DSApp)
    }
    
    class FedCat["Federated Catalogue"]
    class DataApp["Data App"] {
        packageId: String
        packageLocation: String
    }
    
    class RemoteClient["Remote Client"] {
        endpoint: String
    }
    class DatasetOffer["Dataset Offer"] {
        dataset: Dataset
        offerPolicy: OdrlPolicy
    }

    class DatasetOffer2["Dataset Offer"] {
        dataset: Dataset
        offerPolicy: OdrlPolicy
    }

    class ExternalSystem["Legacy System"] {
        <<external>>
    }

    class EcosystemApp ["Ecosystem App"] {
        <<external>>
    }

    DPI *-- "1..*" Node
    ComponentManager ..> "1..*" Component : manages
    EcosystemApp ..> "1..*" Node : uses services

    Connector2  ..> "1" BackingService : wraps

    Node  ..> "1..*" BackingService : uses

    Node  *-- "1..*" Component
    Component --> "1..*" Interface : implements
    Interface *-- "1..*" Primitive : defines

    Component <|-- Service
    Component <|-- Remote Client
    Component <|-- DataApp
    Component --> "0..*" Connector : builds on

    Service <|-- VisibilityService
    Service <|-- DXService
    Service <|-- FedService
    DataApp <|-- Adaptor

    Adaptor ..> ExternalSystem : adapts

    DXService <.. DSConnector : instance of
    FedCat ..> FedService : instance of

    Node "1" -- "1..*" DatasetOffer2
    FedCat "1" -- "1..*" DatasetOffer : registered

    Node *-- "1" ComponentManager





