---
config:
  theme: default
---
sequenceDiagram
    %% Define participants with aliases for cleaner labels
    participant C as Data Consumer
    participant FCAT as Fed Catalogue
    participant PNP as Policy Negotiation
    participant RM as Rights Management
    participant DSC as Data Provider <br>Control Plane
    participant DSD as Data Provider <br>Data Plane
    participant ADP as TWIN Adaptor<br>DS App
    autonumber

    activate C
    C->>+FCAT: catalog request(query)
    FCAT-->>-C : matching datasets

    C->>+PNP: Negotiate(Dataset,Offer)
    activate PNP
    PNP->>-PNP: verify
    Note left of PNP: Eclipse DSP

    PNP->>+RM: decide
    RM-->>-PNP: accepted
    PNP-->>-C: negotiation Agreement

    C->>+DSC: Request Transfer (Pull)
    Note left of DSC: Eclipse DSP
    DSC-->>-C: Transfer started

    C->>+DSD: Query Data Asset
    DSD->>+ADP: handleDataRequest
    ADP-->>-DSD: data
    DSD-->>-C: Query Result (JSON-LD)

    deactivate C